# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kastelo labs, inc
email: danny@kastelo.co
description: > # this means to ignore newlines until "baseurl:"
  We build awesome iOS and Rails applications!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kastelolabs.co" # the base hostname & protocol for your site
# enforce_ssl: kastelolabs.co
twitter_username: kastelolabs
github_username:  kastelolabs

# Build settings
markdown: kramdown

exclude: [README.md]
